=== hmcts/cpp-context-defence/defence-event/defence-event-processor/src/yaml/json/schema/defence.command.receive-defence-client.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cpp/defence/event/processor/commands/receive-defence-client.json",
  "type": "object",
  "properties": {
    "defenceClientId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "urn": {
       "type": "string"
    },
    "defendantDetails": {
      "$ref": "http://justice.gov.uk/cps/defence/defendant-details.json"
    },
    "defenceClientDetails": {
      "$ref": "http://justice.gov.uk/cps/defence/defence-client-details"
    },
    "defendantId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    }
  },
  "additionalProperties": false,
  "required": [
    "defenceClientId",
    "defendantDetails",
    "defenceClientDetails"
  ]
}

=== hmcts/cpp-context-defence/defence-command/defence-command-handler/src/test/resources/json/receiveADefenceClient.json
{
  "defenceClientId": "a4391788-f829-4514-a344-61f1d5d9690c",
  "urn": "55DP0028116",
  "defendantDetails": {
    "caseId": "a4391788-f829-4514-a344-61f1d5d9690c",
    "id": "39a2572c-db47-473d-b1b8-69836ad5da2a",
    "firstName": "JOHNNY",
    "lastName": "WRONGUN",
    "dateOfBirth": "1985-10-17"
  },
  "defenceClientDetails": {
    "asn": "asn",
    "bailConditions": "Lorem ipsum dolor sit amet",
    "bailDate": "2015-02-15",
    "policeRemandStatus": "Remanded on conditional bail",
    "policePersonId": "policePersonId"
  }
}
