=== hmcts/cpp-context-defence/defence-event/defence-event-processor/src/yaml/json/schema/defence.event.idpc-access-by-organisation-recorded.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/defence/json/schema/event/idpc-access-by-organisation-recorded.json",
  "type": "object",
  "properties": {
    "defenceClientId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "defenceClientSurname": {
      "type": "string"
    },
    "defenceClientOrganisationName": {
      "type": "string"
    },
    "userId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "organisationId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "materialId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "accessTimestamp": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date-time"
    },
    "caseUrn": {
       "type": "string"
    }
  },
  "oneOf": [
    {
      "required": [
        "defenceClientId",
        "defenceClientSurname",
        "userId",
        "organisationId",
        "materialId",
        "accessTimestamp"
      ]
    },
    {
      "required": [
        "defenceClientId",
        "defenceClientOrganisationName",
        "userId",
        "organisationId",
        "materialId",
        "accessTimestamp"
      ]
    }
  ]
}

=== hmcts/cpp-context-defence/defence-event/defence-event-processor/src/yaml/json/defence.event.idpc-access-by-organisation-recorded.json
{
  "defenceClientId": "0d2b7de7-c364-4a39-a87c-012ec06f4990",
  "defenceClientSurname": "WRONGUN",
  "userId": "0d2b7de7-c364-4a39-a87c-012ec06f4990",
  "organisationId": "45e4dff9-581d-4f56-bb15-8303cf43dc87",
  "materialId": "45e4dff9-f829-4514-a344-61f1d5d9690c",
  "accessTimestamp":"2018-03-27T15:32:33.471Z",
  "caseUrn": "55DP0028116"
}

=== hmcts/cpp-context-defence/defence-command/defence-command-handler/src/test/resources/json/idpcAccessByOrganisationRecorded.json
{
  "accessTimestamp": "2018-03-27T15:32:33.471Z",
  "defenceClientId": "a4391788-f829-4514-a344-61f1d5d9690c",
  "defenceClientSurname": "smith",
  "materialId": "45e4dff9-f829-4514-a344-61f1d5d9690c",
  "organisationId": "45e4dff9-581d-4f56-bb15-8303cf43dc87",
  "userId": "0d2b7de7-c364-4a39-a87c-012ec06f4990"
}
