=== hmcts/cpp-context-defence/defence-event/defence-event-processor/src/yaml/json/schema/public.defence.case-assigned-to-prosecutor.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/defence/json/schema/event/public.defence.case-assigned-to-prosecutor.json",
  "type": "object",
  "properties": {
    "caseId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "assigneeOrganisation": {
      "$ref": "http://moj.gov.uk/cpp/defence/organisation.json"
    },
    "assigneeDetails": {
      "$ref": "http://justice.gov.uk/cps/defence/person-details.json"
    },
    "assignorDetails": {
      "$ref": "http://justice.gov.uk/cps/defence/person-details.json"
    },
    "assignorOrganisation": {
      "$ref": "http://moj.gov.uk/cpp/defence/organisation.json"
    },
    "assignmentTimestamp": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date-time"
    },
    "representingOrganisation": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "caseId",
    "assigneeOrganisation",
    "assigneeDetails",
    "assignorDetails",
    "assignorOrganisation",
    "assignmentTimestamp",
    "representingOrganisation"
  ]
}

=== hmcts/cpp-context-defence/defence-integration-test/src/test/resources/public.defence.event.case-assigned-to-advocate-noncps.json
{
  "assigneeDetails": {
    "firstName": "Richard",
    "lastName": "Chapman",
    "userId": "ASSIGNEE_ID"
  },
  "assigneeOrganisation": {
    "address": {
      "address1": "Legal House",
      "address2": "15 Sewell Street",
      "address3": "Hammersmith",
      "address4": "London",
      "addressPostcode": "SE14 2AB"
    },
    "orgId": "ORG_ID",
    "organisationName": "Bodgit and Scarper LLP"
  },
  "assignmentTimestamp": "2021-12-02T15:26:36.877Z",
  "assignorDetails": {
    "firstName": "Richard",
    "lastName": "Chapman",
    "userId": "ASSIGNOR_ID"
  },
  "assignorOrganisation": {
    "address": {
      "address1": "Legal House",
      "address2": "15 Sewell Street",
      "address3": "Hammersmith",
      "address4": "London",
      "addressPostcode": "SE14 2AB"
    },
    "orgId": "ORG_ID",
    "organisationName": "Bodgit and Scarper LLP"
  },
  "representingOrganisation": "DVLA",
  "caseId": "CASE_ID"
}
