=== hmcts/cpp-context-defence/defence-event/defence-event-listener/src/yaml/json/schema/defence.events.cases-assigned-to-advocate.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cpp/defence/events/defence.events.cases-assigned-to-advocate.json",
  "type": "object",
  "properties": {
    "caseHearingAssignments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "caseId": {
            "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
          },
          "hearingId": {
            "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
          },
          "prosecutingAuthorityId": {
            "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
          },
          "isCps": {
            "type": "boolean"
          },
          "isPolice": {
            "type": "boolean"
          }
        },
        "required": [
          "caseId",
          "hearingId",
          "prosecutingAuthorityId"
        ]
      }
    },
    "assigneeOrganisation": {
      "$ref": "http://moj.gov.uk/cpp/defence/organisation.json"
    },
    "assigneeDetails": {
      "$ref": "http://justice.gov.uk/cps/defence/person-details.json"
    },
    "assignorDetails": {
      "$ref": "http://justice.gov.uk/cps/defence/person-details.json"
    },
    "assignorOrganisation": {
      "$ref": "http://moj.gov.uk/cpp/defence/organisation.json"
    },
    "assignmentTimestamp": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date-time"
    },
    "representingOrganisation": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "caseHearingAssignments",
    "assigneeOrganisation",
    "assigneeDetails",
    "assignorDetails",
    "assignorOrganisation",
    "assignmentTimestamp",
    "representingOrganisation"
  ]
}

=== hmcts/cpp-context-defence/defence-integration-test/src/test/resources/public.defence.event.case-assigned-to-advocate-noncps-by-hearing.json
{
  "assigneeDetails": {
    "firstName": "Richard",
    "lastName": "Chapman",
    "userId": "ASSIGNEE_ID"
  },
  "assigneeOrganisation": {
    "address": {
      "address1": "Legal House",
      "address2": "15 Sewell Street",
      "address3": "Hammersmith",
      "address4": "London",
      "addressPostcode": "SE14 2AB"
    },
    "orgId": "ORG_ID",
    "organisationName": "Bodgit and Scarper LLP"
  },
  "assignmentTimestamp": "2021-12-02T15:26:36.877Z",
  "assignorDetails": {
    "firstName": "Richard",
    "lastName": "Chapman",
    "userId": "ASSIGNOR_ID"
  },
  "assignorOrganisation": {
    "address": {
      "address1": "Legal House",
      "address2": "15 Sewell Street",
      "address3": "Hammersmith",
      "address4": "London",
      "addressPostcode": "SE14 2AB"
    },
    "orgId": "ORG_ID",
    "organisationName": "Bodgit and Scarper LLP"
  },
  "caseHearingAssignments": [
    {
      "caseId": "CASE_ID",
      "hearingId": "HEARING_ID",
      "isCps": true,
      "isPolice": true,
      "prosecutingAuthorityId": "42880989-5d09-332e-a711-8797af06ecea"
    }
  ],
  "representingOrganisation": "DVLA"
}

=== hmcts/cpp-context-defence/defence-event/defence-event-listener/src/yaml/json/defence.events.cases-assigned-to-organisation.json
{
  "assigneeDetails": {
    "firstName": "Richard",
    "lastName": "Chapman",
    "userId": "cab8f139-c0f5-4b0e-ac37-8090d19786ef"
  },
  "assigneeOrganisation": {
    "address": {
      "address1": "Legal House",
      "address2": "15 Sewell Street",
      "address3": "Hammersmith",
      "address4": "London",
      "addressPostcode": "SE14 2AB"
    },
    "orgId": "7e48c19c-b92f-4c16-8e53-b26b70c6b202",
    "organisationName": "Bodgit and Scarper LLP"
  },
  "assignmentTimestamp": "2022-05-15T12:00:30.215Z",
  "assignorDetails": {
    "firstName": "Richard",
    "lastName": "Chapman",
    "userId": "06ca175b-f3cd-4a5a-abdd-a9156238f538"
  },
  "assignorOrganisation": {
    "address": {
      "address1": "Legal House",
      "address2": "15 Sewell Street",
      "address3": "Hammersmith",
      "address4": "London",
      "addressPostcode": "SE14 2AB"
    },
    "orgId": "7e48c19c-b92f-4c16-8e53-b26b70c6b202",
    "organisationName": "Bodgit and Scarper LLP"
  },
  "caseHearingAssignments": [
    {
      "caseId": "dfbcc2b0-2c78-4b03-bc54-7e14dc7a08ea",
      "hearingId": "654c4568-62f3-480a-bcaa-72869fae14db",
      "isCps": true,
      "isPolice": true,
      "prosecutingAuthorityId": "bdc190e7-c939-37ca-be4b-9f615d6ef40e"
    }
  ],
  "representingOrganisation": "CPS"
}
