=== hmcts/cpp-context-defence/defence-domain/defence-domain-event/src/raml/json/schema/defence.event.access-granted.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/cps/defence/events/access-granted",
  "type": "object",
  "properties": {
    "defendantId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "permissions": {
      "type": "array",
      "items": {
        "$ref": "http://justice.gov.uk/cps/defence/permission.json"
      }
    },
    "granteeOrganisation": {
      "$ref": "http://moj.gov.uk/cpp/defence/organisation.json"
    },
    "granteeDetails": {
      "$ref": "http://justice.gov.uk/cps/defence/person-details.json"
    },
    "granterDetails": {
      "$ref": "http://justice.gov.uk/cps/defence/person-details.json"
    }
  },
  "required": [
    "defendantId",
    "permissions",
    "granteeOrganisation",
    "granteeDetails",
    "granterDetails"
  ]
}

=== hmcts/cpp-context-defence/defence-event/defence-event-listener/src/yaml/json/defence.event.access-granted.json
{
  "defendantId" : "7597f9bd-060e-4a0d-bd80-85b9778fcd7b",
  "permissions" : [
    {
      "id": "db5f9bfa-6e11-4d45-ba69-d106de45c339",
      "description": "Permission",
      "source": "b84dd6a8-7fb6-4018-b66d-a4037fda15a6",
      "target": "7597f9bd-060e-4a0d-bd80-85b9778fcd7b",
      "object": "DefenceClient",
      "action": "View"
    },
    {
      "id": "db5f9bfa-6e11-4d45-ba69-d106de45c339",
      "description": "Permission",
      "source": "b84dd6a8-7fb6-4018-b66d-a4037fda15a6",
      "target": "7597f9bd-060e-4a0d-bd80-85b9778fcd7b",
      "object": "DefendantDocuments",
      "action": "View"
    },
    {
      "id": "db5f9bfa-6e11-4d45-ba69-d106de45c339",
      "description": "Permission",
      "source": "b84dd6a8-7fb6-4018-b66d-a4037fda15a6",
      "target": "7597f9bd-060e-4a0d-bd80-85b9778fcd7b",
      "object": "DefendantDocuments",
      "action": "Upload"
    }
  ],
  "granteeOrganisation": {
    "orgId": "4ff376b9-2acb-4de9-8a7b-fedd3a6e5b1a",
    "organisationName": "Co Ltd",
    "address": {
      "address1": "Line 1",
      "address4": "Line 2",
      "addressPostcode": "xu 45tr"
    }
  },
  "granteeDetails" : {
    "userId": "4ff376b9-2acb-4de9-8a7b-fedd3a6e5b1a",
    "firstName": "Grantee First Name",
    "lastName": "Last Name",
    "dateOfBirth": "20/02/1989"
  },
"granterDetails" : {
  "userId": "4ff376b9-2acb-4de9-8a7b-fedd3a6e5b1a",
  "firstName": "Grantee First Name",
  "lastName": "Last Name",
  "dateOfBirth": "20/02/1989"
}
}
